sudo: false
language: python
before_install:
  - pip install codecov
install:
  - pip install -q coverage
  - pip install pylint
  - pip install -r requirements.txt
python:
  - 3.5
script: nosetests --with-coverage
cache: pip
